# Generated by Django 2.1.5 on 2019-02-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula_Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.BooleanField()),
                ('numerator', models.BooleanField()),
                ('denominator', models.BooleanField()),
                ('exponent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Objective')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=0, max_digits=5)),
                ('numerator', models.DecimalField(decimal_places=0, max_digits=5)),
                ('denominator', models.DecimalField(decimal_places=0, max_digits=5)),
                ('exponent', models.DecimalField(decimal_places=0, max_digits=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Question')),
            ],
        ),
        migrations.AddField(
            model_name='formula_parameters',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Objective'),
        ),
    ]
