# Generated by Django 2.1.5 on 2019-02-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='description',
            new_name='objective_text',
        ),
    ]
